# Generated by Django 4.0.4 on 2022-05-28 11:45

import common.validators
from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicTx',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_derivation_path', models.TextField(help_text='Derivation path for from address')),
                ('from_address', models.TextField()),
                ('to_derivation_path', models.TextField(help_text='Derivation path for to address')),
                ('to_address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, validators=[common.validators.validate_positive])),
                ('description', models.TextField()),
                ('unsigned_transaction', models.TextField(blank=True, help_text='Base58 encoded unsigned transaction')),
                ('fireblocks_tx_id', models.TextField(blank=True)),
                ('signed_transaction', models.TextField(blank=True, help_text='Base58 encoded signed transaction')),
                ('status', django_fsm.FSMField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('awaiting_signature', 'Awaiting signature'), ('signed', 'Signed'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='new', max_length=30)),
                ('avalanche_tx_id', models.TextField(blank=True)),
            ],
        ),
    ]
