# Generated by Django 4.0.4 on 2022-06-14 11:05

import uuid

import django_fsm

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalanche', '0002_alter_atomictx_options_alter_atomictx_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomictx',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('awaiting_signature', 'Awaiting signature'), ('signed', 'Signed'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='ChainSwap',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('new', 'New'), ('exporting', 'Exporting'), ('exported', 'Exported'), ('importing', 'Importing'), ('complete', 'Complete'), ('failed', 'Failed')], default='new', max_length=30)),
                ('export_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avalanche.atomictx')),
                ('import_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avalanche.atomictx')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
