# Generated by Django 4.0.4 on 2022-06-14 15:48

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('avalanche', '0003_alter_atomictx_status_chainswap'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainswap',
            name='source_chain',
            field=models.CharField(default='C', help_text='Either C or P', max_length=1, validators=[common.validators.validate_p_or_c]),
            preserve_default=False,
        ),
    ]
