# Generated by Django 4.0.4 on 2022-06-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalanche', '0004_chainswap_source_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainswap',
            name='import_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avalanche.atomictx'),
        ),
    ]
