name: Django CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


env:
  DJANGO_SETTINGS_MODULE: ss.settings.fuji
  FIREBLOCKS_XPUB: xpub6DQ3APZH2r7AyZvb1eCK7FEjJG23akaYr5otgyegb3WuJsuiUtX3sJXn7YaAzL42bRDxVF6xUXRkx9hE2wKGfg3cJvdoZUDAQEktupur7r7
  FIREBLOCKS_PRIVATE_KEY: fireblocks_secret.key
  FIREBLOCKS_API_KEY: apikey
  CONTRACT_STAKING: 0xd61177578B59cb50736e6ccB4c3262437124bA71
  CONTRACT_ORACLE: 0xd61177578B59cb50736e6ccB4c3262437124bA71
  CUSTODY_WALLET_ADDRESS: 0xd61177578B59cb50736e6ccB4c3262437124bA71

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.5]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements_dev.txt
    - name: Create .env file
      run: |
        cp example.env .env
    - name: Run Tests
      run: |
        python ss/manage.py test
